# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  [
    "debian-stretch64",
    "debian-jessie64",
#    "generic-fedora28", # The Fedora deployment doesn't work inside here at the moment.
#    "generic-fedora29",
    "generic-arch"
  ].each { |distro_name|
    config.vm.define distro_name do |vm|
      vm.vm.box = distro_name.sub('-', '/') # We can't have slashes in the subvm name
      vm.vm.provision "ansible" do |ansible|
        ansible.playbook = "test.yml"
      end
    end
  }
end
